/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package recursive.type.bound;

public class App {
  public String getGreeting() { return "Hello World!"; }

  public static void main(String[] args) {
    System.out.println(new App().getGreeting());
    Child child = new Child();
    Child child2 = child.returnSelf();
  }

  public abstract static class Parent<Self extends Parent<Self>> {
    @SuppressWarnings("unchecked")
    protected Self returnSelf() {
      return (Self)this;
    }
  }

  public static class Child extends Parent<Child> {
  }
}
